version: '3.5'

volumes:
  local_postgres_data: {}
  media_volume: {}


services:
  # database
  gu_db:
    image: postgres:15.2
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      # - ./entrypoint.sh:s/app/entrypoint.sh
    environment:
      POSTGRES_HOST: gu_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: kiki
      POSTGRES_USER: imaginos
      POSTGRES_PASSWORD: ca
      
    ports:
      - '5432:5432'
  # backend
  django:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src
      - media_volume:/var/www/media/
    ports:
      - '8000:8000'
    depends_on:
      - gu_db
  # frontend
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - django
  # database management
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - gu_db
